const char *HTML_FORM =
"<!DOCTYPE html>"
"<html lang=\"es\">"
"<head>"
"  <meta charset=\"UTF-8\">"
"  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">"
"  <title>Configuración del Variador</title>"
"  <style>"
"    body{font-family:system-ui,-apple-system,Segoe UI,Roboto,sans-serif;background:#f8f9fa;margin:0;}"
"    .container{max-width:960px;margin:0 auto;padding:1rem;}"
"    h1{font-size:1.8rem;margin-bottom:1.5rem;}"
"    .row{display:flex;flex-wrap:wrap;margin:-0.5rem;}"
"    .col-md-4{flex:0 0 100%;max-width:100%;padding:0.5rem;}"
"    @media (min-width:768px){.col-md-4{flex:0 0 33.3333%;max-width:33.3333%;}}"
"    .form-label{display:block;font-weight:600;margin-bottom:0.25rem;font-size:0.95rem;}"
"    .form-control,.form-select{display:block;width:100%;padding:0.375rem 0.75rem;"
"      font-size:1rem;line-height:1.5;color:#212529;background-color:#fff;"
"      border:1px solid #ced4da;border-radius:0.25rem;box-sizing:border-box;}"
"    .form-control:focus,.form-select:focus{outline:2px solid #0d6efd33;outline-offset:1px;}"
"    .btn{display:inline-block;font-weight:400;line-height:1.5;text-align:center;"
"      text-decoration:none;border:1px solid transparent;padding:0.375rem 0.75rem;"
"      font-size:1rem;border-radius:0.25rem;cursor:pointer;margin:1.5rem;}"
"    .btn-primary{color:#fff;background-color:#0d6efd;border-color:#0d6efd;width:100%;}"
"    .btn-primary:hover{background-color:#0b5ed7;border-color:#0a58ca;}"
"    .btn-success{color:#fff;background-color:#198754;border-color:#198754;}"
"    .btn-danger{color:#fff;background-color:#dc3545;border-color:#dc3545;}"
"    .btn-success:hover{background-color:#157347;border-color:#146c43;}"
"    .btn-danger:hover{background-color:#bb2d3b;border-color:#b02a37;}"
"    .mb-4{margin-bottom:1.5rem;}"
"    .mt-4{margin-top:1.5rem;}"
"    .py-4{padding-top:1.5rem;padding-bottom:1.5rem;}"
"    .me-2{margin-right:0.5rem;}"
"  </style>"
"</head>"
"<body class=\"bg-light\">"
"<div class=\"container py-4\">"
"  <h1 class=\"mb-4\">Configuración del Variador</h1>"
"  <form id=\"config-form\" method=\"POST\" action=\"/save\" class=\"row g-3\">"

"    <div class=\"col-md-4\">"
"      <label class=\"form-label\">Frecuencia de operación (Hz)</label>"
"      <input type=\"number\" class=\"form-control\" name=\"frequency\" min=\"1\" max=\"150\" required>"
"    </div>"

"    <div class=\"col-md-4\">"
"      <label class=\"form-label\">Aceleración (Hz/s)</label>"
"      <input type=\"number\" class=\"form-control\" name=\"accel\" min=\"1\" max=\"50\" required>"
"    </div>"

"    <div class=\"col-md-4\">"
"      <label class=\"form-label\">Desaceleración (Hz/s)</label>"
"      <input type=\"number\" class=\"form-control\" name=\"decel\" min=\"1\" max=\"50\" required>"
"    </div>"

"    <div class=\"col-md-4\">"
"      <label class=\"form-label\">Variación de las entradas</label>"
"      <select class=\"form-select\" name=\"variation\" required>"
"        <option value=\"lineal\">Lineal</option>"
"        <option value=\"cuadratica\">Cuadrática</option>"
"      </select>"
"    </div>"

"    <div class=\"col-md-4\">"
"      <label class=\"form-label\">Corriente máx. bus DC (mA)</label>"
"      <input type=\"number\" class=\"form-control\" name=\"imax\" min=\"500\" max=\"2000\" required>"
"    </div>"

"    <div class=\"col-md-4\">"
"      <label class=\"form-label\">Tensión máx. bus DC (V)</label>"
"      <input type=\"number\" class=\"form-control\" name=\"vmin\" min=\"250\" max=\"350\" required>"
"    </div>"

"    <div class=\"col-md-4\">"
"      <label class=\"form-label\">Hora del sistema (HH:mm:ss)</label>"
"      <input type=\"text\" class=\"form-control\" name=\"sys_time\" placeholder=\"12:34:56\" required>"
"    </div>"

"    <div class=\"col-md-4\">"
"      <label class=\"form-label\">Horario de arranque (HH:mm)</label>"
"      <input type=\"text\" class=\"form-control\" name=\"start_time\" placeholder=\"08:00\" required>"
"    </div>"

"    <div class=\"col-md-4\">"
"      <label class=\"form-label\">Horario de parada (HH:mm)</label>"
"      <input type=\"text\" class=\"form-control\" name=\"stop_time\" placeholder=\"18:00\" required>"
"    </div>"

"    <div class=\"col-12 mt-4\">"
"      <button type=\"submit\" class=\"btn btn-primary me-2\" name=\"cmd\" value=\"save\">Guardar configuración</button>"
"      <button type=\"submit\" class=\"btn btn-success me-2\" name=\"cmd\" value=\"start\">Arrancar motor</button>"
"      <button type=\"submit\" class=\"btn btn-danger\" name=\"cmd\" value=\"stop\">Parar motor</button>"
"    </div>"
"  </form>"
"</div>"

"<script>"
"  const formId = 'config-form';"
"  const storageKey = 'variador_form_state';"
"  function saveFormState() {"
"    const form = document.getElementById(formId);"
"    if (!form) return;"
"    const data = {};"
"    Array.from(form.elements).forEach(el => {"
"      if (!el.name) return;"
"      if (el.type === 'checkbox' || el.type === 'radio') {"
"        data[el.name] = el.checked;"
"      } else {"
"        data[el.name] = el.value;"
"      }"
"    });"
"    try {"
"      localStorage.setItem(storageKey, JSON.stringify(data));"
"    } catch (e) {"
"      console.log('No se pudo guardar estado:', e);"
"    }"
"  }"
"  function loadFormState() {"
"    const form = document.getElementById(formId);"
"    if (!form) return;"
"    const raw = localStorage.getItem(storageKey);"
"    if (!raw) return;"
"    try {"
"      const data = JSON.parse(raw);"
"      Array.from(form.elements).forEach(el => {"
"        if (!el.name || !(el.name in data)) return;"
"        if (el.name === 'cmd') return;"
"        if (el.type === 'checkbox' || el.type === 'radio') {"
"          el.checked = !!data[el.name];"
"        } else {"
"          el.value = data[el.name];"
"        }"
"      });"
"    } catch (e) {"
"      console.log('No se pudo leer estado:', e);"
"    }"
"  }"
"  window.addEventListener('load', () => {"
"    loadFormState();"
"    const form = document.getElementById(formId);"
"    if (!form) return;"
"    form.addEventListener('input', saveFormState);"
"  });"
"</script>"

"</body>"
"</html>";
