var annotated_dup =
[
    [ "bitmap_t", "structbitmap__t.html", "structbitmap__t" ],
    [ "frequency_settings_SH1106_t", "structfrequency__settings___s_h1106__t.html", "structfrequency__settings___s_h1106__t" ],
    [ "frequency_settings_t", "structfrequency__settings__t.html", "structfrequency__settings__t" ],
    [ "MCP23017_DEFVAL_t", "union_m_c_p23017___d_e_f_v_a_l__t.html", "union_m_c_p23017___d_e_f_v_a_l__t" ],
    [ "MCP23017_GPINTEN_t", "union_m_c_p23017___g_p_i_n_t_e_n__t.html", "union_m_c_p23017___g_p_i_n_t_e_n__t" ],
    [ "MCP23017_GPIO_t", "union_m_c_p23017___g_p_i_o__t.html", "union_m_c_p23017___g_p_i_o__t" ],
    [ "MCP23017_GPPU_t", "union_m_c_p23017___g_p_p_u__t.html", "union_m_c_p23017___g_p_p_u__t" ],
    [ "MCP23017_INTCAP_t", "union_m_c_p23017___i_n_t_c_a_p__t.html", "union_m_c_p23017___i_n_t_c_a_p__t" ],
    [ "MCP23017_INTCON_t", "union_m_c_p23017___i_n_t_c_o_n__t.html", "union_m_c_p23017___i_n_t_c_o_n__t" ],
    [ "MCP23017_INTF_t", "union_m_c_p23017___i_n_t_f__t.html", "union_m_c_p23017___i_n_t_f__t" ],
    [ "MCP23017_IOCON_t", "union_m_c_p23017___i_o_c_o_n__t.html", "union_m_c_p23017___i_o_c_o_n__t" ],
    [ "MCP23017_IODIR_t", "union_m_c_p23017___i_o_d_i_r__t.html", "union_m_c_p23017___i_o_d_i_r__t" ],
    [ "MCP23017_IPOL_t", "union_m_c_p23017___i_p_o_l__t.html", "union_m_c_p23017___i_p_o_l__t" ],
    [ "MCP23017_OLAT_t", "union_m_c_p23017___o_l_a_t__t.html", "union_m_c_p23017___o_l_a_t__t" ],
    [ "rtc_alarms_t", "structrtc__alarms__t.html", "structrtc__alarms__t" ],
    [ "seccurity_settings_SH1106_t", "structseccurity__settings___s_h1106__t.html", "structseccurity__settings___s_h1106__t" ],
    [ "seccurity_settings_t", "structseccurity__settings__t.html", "structseccurity__settings__t" ],
    [ "sh1106_t", "structsh1106__t.html", "structsh1106__t" ],
    [ "spi_cmd_item_t", "structspi__cmd__item__t.html", "structspi__cmd__item__t" ],
    [ "system_status_t", "structsystem__status__t.html", "structsystem__status__t" ],
    [ "time_settings_SH1106_t", "structtime__settings___s_h1106__t.html", "structtime__settings___s_h1106__t" ],
    [ "time_settings_t", "structtime__settings__t.html", "structtime__settings__t" ]
];